name: CI with SonarCloud

on:
  push:
    branches:
      - main # Analisar sempre que houver um push para a main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        # O Sonar precisa do histórico completo do Git
        with:
          fetch-depth: 0 

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21' 
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Build and SonarCloud Scan
        # Comando para correr o SonarCloud. Atenção ao projectKey!
        run: mvn clean verify sonar:sonar \
          -Dsonar.projectKey=o_seu_project_key_aqui \
          -Dsonar.organization=o_seu_id_de_organizacao_aqui \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}